version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
  web:
    build: .
    ports:
      - "3031:3030"
    links:
      - db:db

volumes:
  db_data:     
