version: "3"
services:
  db:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - db_data:/data/db
  web:
    build: .
    ports:
      - "3030:3030"
    links:
      - db:db

volumes:
  db_data:     
